import type { CatalogEntry } from "./types";

const DOCS = "https://docs.github.com/en/copilot/concepts/agents/copilot-cli";

export const copilotEntries: CatalogEntry[] = [
  {
    id: "cp.user.settings",
    tool: "copilot-cli",
    scope: "user",
    category: "settings",
    label: "settings.json",
    pathTemplate: "{copilot_home}/settings.json",
    kind: "file",
    language: "json",
    schemaId: "copilot-settings",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.mcp",
    tool: "copilot-cli",
    scope: "user",
    category: "mcp",
    label: "mcp-config.json",
    pathTemplate: "{copilot_home}/mcp-config.json",
    kind: "file",
    language: "json",
    schemaId: "mcp-config",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.lsp",
    tool: "copilot-cli",
    scope: "user",
    category: "settings",
    label: "lsp-config.json",
    pathTemplate: "{copilot_home}/lsp-config.json",
    kind: "file",
    language: "json",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.agents",
    tool: "copilot-cli",
    scope: "user",
    category: "agents",
    label: "Agents",
    pathTemplate: "{copilot_home}/agents",
    kind: "dir-of-files",
    fileGlob: "*.agent.md",
    language: "markdown",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.skills",
    tool: "copilot-cli",
    scope: "user",
    category: "skills",
    label: "Skills",
    pathTemplate: "{copilot_home}/skills",
    kind: "dir-of-files",
    fileGlob: "*/SKILL.md",
    language: "markdown",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.hooks",
    tool: "copilot-cli",
    scope: "user",
    category: "hooks",
    label: "Hooks",
    pathTemplate: "{copilot_home}/hooks",
    kind: "dir-of-files",
    fileGlob: "*",
    language: "markdown",
    docsUrl: DOCS,
  },
  {
    id: "cp.project.mcp",
    tool: "copilot-cli",
    scope: "project",
    category: "mcp",
    label: ".copilot/mcp-config.json",
    pathTemplate: "{project}/.copilot/mcp-config.json",
    kind: "file",
    language: "json",
    schemaId: "mcp-config",
    docsUrl: DOCS,
  },
  {
    id: "cp.project.agents",
    tool: "copilot-cli",
    scope: "project",
    category: "agents",
    label: ".github/agents",
    pathTemplate: "{project}/.github/agents",
    kind: "dir-of-files",
    fileGlob: "*.md",
    language: "markdown",
    docsUrl: DOCS,
  },
  {
    id: "cp.project.hooks",
    tool: "copilot-cli",
    scope: "project",
    category: "hooks",
    label: ".github/hooks",
    pathTemplate: "{project}/.github/hooks",
    kind: "dir-of-files",
    fileGlob: "*",
    language: "markdown",
    docsUrl: DOCS,
  },
  {
    id: "cp.user.env",
    tool: "copilot-cli",
    scope: "user",
    category: "env",
    label: "Environment Variables",
    pathTemplate: "",
    kind: "env",
    language: "env",
    docsUrl: DOCS,
    envVars: [
      "COPILOT_HOME",
      "COPILOT_CACHE_HOME",
      "GITHUB_TOKEN",
      "GH_TOKEN",
      "HTTPS_PROXY",
      "HTTP_PROXY",
      "NO_PROXY",
    ],
  },
];
